# Generated by Django 2.2.3 on 2019-11-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebTVLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WebTVMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('media_type', models.CharField(choices=[('I', 'Image'), ('V', 'Video')], default='I', max_length=1)),
                ('media', models.FileField(blank=True, default=None, null=True, upload_to='tv')),
                ('activate', models.BooleanField(default=False)),
                ('times', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WebTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tv.WebTVLink')),
            ],
        ),
    ]
