# Generated by Django 2.2.3 on 2019-11-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtvlink',
            name='url',
            field=models.URLField(),
        ),
    ]
