# Generated by Django 2.2.3 on 2019-10-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('default', models.BooleanField(default=False)),
                ('is_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='tvconfiguration',
            name='enable_messages',
        ),
    ]
