# Generated by Django 2.2.3 on 2019-10-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0002_auto_20191003_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('media', models.FileField(blank=True, default=None, null=True, upload_to='tv')),
            ],
        ),
        migrations.RemoveField(
            model_name='tvconfiguration',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='tvconfiguration',
            name='photo',
        ),
    ]
