# Generated by Django 3.2.16 on 2023-03-30 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semestre')),
            ],
        ),
    ]
