# Generated by Django 2.2.3 on 2021-08-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('publication_date', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
    ]
