# Generated by Django 2.2.3 on 2021-08-24 16:24

import core.services.current_semester
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210206_1707'),
        ('chopin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('responsable', models.CharField(default=None, max_length=255, null=True)),
                ('periode', models.CharField(max_length=5, null=True)),
                ('hour', models.TimeField(null=True)),
                ('semestre', models.ForeignKey(default=core.services.current_semester.get_current_semester, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Semestre')),
            ],
        ),
    ]
