# Generated by Django 2.2.3 on 2021-08-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chopin', '0002_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
