# Generated by Django 2.2.3 on 2021-09-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0020_etudiant_groupe_reservation'),
        ('chopin', '0003_calendar_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningCreneau',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hour', models.TimeField()),
                ('duree', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanningJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('descroption', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('id_perm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perm.Creneau')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningTypeJour',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanningRepartission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_creneau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perm.Creneau')),
                ('id_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chopin.PlanningJob')),
                ('id_membre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chopin.PlanningMember')),
            ],
        ),
        migrations.CreateModel(
            name='PlanningCota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb', models.IntegerField()),
                ('id_creneau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chopin.PlanningCreneau')),
                ('id_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chopin.PlanningJob')),
                ('id_typejour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chopin.PlanningTypeJour')),
            ],
        ),
    ]
