# Generated by Django 2.2.1 on 2019-07-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('periode', models.CharField(choices=[('A', 'Automne'), ('P', 'Printemps')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=16, unique=True)),
                ('right', models.CharField(choices=[('A', 'Accès total'), ('P', 'Accès articles'), ('N', 'Accès interdit')], max_length=1)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
