# Generated by Django 2.2.3 on 2019-09-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeTVA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('state', models.CharField(choices=[('N', 'Non déclarée'), ('D', 'Déclarée')], default='N', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='semestre',
            name='solde_debut',
            field=models.IntegerField(default=0),
        ),
    ]
