# Generated by Django 3.2.16 on 2023-05-17 07:30

from django.db import migrations, models
from core.services import ginger as g

def migrate_data(apps,schema_editor):
    Blocked = apps.get_model("core", 'blockeduser')
    ginger = g.GingerClient()
    for blocked in Blocked.objects.all():
        try:
            gingerResponse=ginger.get_badge_info(blocked.badge_uid)
            blocked.badge_uid=gingerResponse["data"]["login"]
            blocked.save()
        except:
            blocked.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
        migrations.AlterField(
            model_name='blockeduser',
            name='badge_uid',
            field=models.CharField(default=None, max_length=8, unique=True),
        ),
        migrations.RenameField(
            model_name='blockeduser',
            old_name='badge_uid',
            new_name='cas',
        ),
    ]
