# Generated by Django 2.2.3 on 2019-09-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190902_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('nom', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
