# Generated by Django 2.2.3 on 2019-09-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(default=None, max_length=50)),
                ('poste_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Poste')),
                ('semestre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Semestre')),
                ('userright_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserRight')),
            ],
        ),
    ]
