# Generated by Django 2.2.3 on 2019-10-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='userright',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
