# Generated by Django 2.2.3 on 2019-10-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userright_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='member'),
        ),
    ]
