# Generated by Django 2.2.3 on 2019-09-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
