# Generated by Django 2.2.3 on 2019-09-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190925_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='poste_id',
        ),
        migrations.AddField(
            model_name='member',
            name='poste_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Poste'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='member',
            name='semestre_id',
        ),
        migrations.AddField(
            model_name='member',
            name='semestre_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Semestre'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='member',
            name='userright_id',
        ),
        migrations.AddField(
            model_name='member',
            name='userright_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.UserRight'),
            preserve_default=False,
        ),
    ]
