# Generated by Django 2.2.3 on 2020-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
