# Generated by Django 2.2.3 on 2019-10-23 09:07

import core.services.current_semester
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190925_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='poste_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Poste'),
        ),
        migrations.AlterField(
            model_name='member',
            name='semestre_id',
            field=models.ForeignKey(default=core.services.current_semester.get_current_semester, on_delete=django.db.models.deletion.CASCADE, to='core.Semestre'),
        ),
    ]
