# Generated by Django 2.2.3 on 2019-10-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191023_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='photo',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='semestre_id',
            new_name='semester_id',
        ),
        migrations.RenameField(
            model_name='poste',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='poste',
            old_name='ordre',
            new_name='order',
        ),
    ]
