# Generated by Django 2.2.3 on 2020-09-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blockeduser_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPerHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=255)),
                ('last_name', models.CharField(default=None, max_length=255)),
                ('user_id', models.CharField(default=None, max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
