# Generated by Django 2.2.3 on 2020-09-12 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_personperhour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personperhour',
            name='date',
        ),
        migrations.AddField(
            model_name='personperhour',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
