# Generated by Django 2.2.3 on 2021-02-06 16:07

import core.services.current_semester
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200912_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='semestre',
            field=models.ForeignKey(default=core.services.current_semester.get_current_semester, on_delete=django.db.models.deletion.CASCADE, to='core.Semestre'),
        ),
    ]
