# Generated by Django 2.2.3 on 2021-08-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('position', models.CharField(choices=[('IN', 'Intérieur'), ('EXT', 'Extérieur')], max_length=3)),
                ('capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150)),
                ('arrivee', models.DateTimeField(auto_now_add=True)),
                ('depart', models.DateTimeField(blank=True, default=None, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='covid.Table')),
            ],
        ),
    ]
