# Generated by Django 3.2.16 on 2023-03-30 08:52

import core.services.current_semester
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perm', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieFactureRecue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactureRecue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva', models.FloatField(default=0)),
                ('prix', models.FloatField(default=0)),
                ('etat', models.CharField(choices=[('D', 'À payer'), ('R', 'À rembourser'), ('E', 'En attente'), ('P', 'Payée')], default='D', max_length=1)),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2023, 3, 30, 10, 52, 27, 497641), null=True)),
                ('date_paiement', models.DateField(default=None, null=True)),
                ('date_remboursement', models.DateField(default=None, null=True)),
                ('moyen_paiement', models.CharField(default=None, max_length=255, null=True)),
                ('personne_a_rembourser', models.CharField(default=None, max_length=255, null=True)),
                ('immobilisation', models.BooleanField(default=False)),
                ('remarque', models.TextField(default=None, null=True)),
                ('facture_number', models.TextField(blank=True, default=None, null=True)),
                ('perm', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_for_picsous', to='perm.creneau')),
                ('semestre', models.ForeignKey(default=core.services.current_semester.get_current_semester, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_for_picsous', to='core.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorieFactureRecue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('nom', models.CharField(max_length=255)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='treso2.categoriefacturerecue')),
            ],
            options={
                'db_table': 'treso2_souscategoriefacturerecue',
            },
        ),
        migrations.CreateModel(
            name='SousCategoriePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField(default=0)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categorie_prix', to='treso2.facturerecue')),
                ('sous_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categorie', to='treso2.souscategoriefacturerecue')),
            ],
            options={
                'db_table': 'treso2_souscategorieprix',
            },
        ),
        migrations.CreateModel(
            name='CategoriePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField(default=0)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='treso2.categoriefacturerecue')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_prix', to='treso2.facturerecue')),
            ],
            options={
                'db_table': 'treso2_categorieprix',
            },
        ),
        migrations.AddConstraint(
            model_name='souscategorieprix',
            constraint=models.UniqueConstraint(fields=('sous_categorie', 'facture'), name='unique sous categorie for facture'),
        ),
        migrations.AddConstraint(
            model_name='souscategoriefacturerecue',
            constraint=models.UniqueConstraint(fields=('categorie', 'code'), name='unique Code for sous categorie'),
        ),
        migrations.AddConstraint(
            model_name='categorieprix',
            constraint=models.UniqueConstraint(fields=('categorie', 'facture'), name='unique categorie for facture'),
        ),
    ]
