# Generated by Django 3.2.16 on 2023-03-30 13:18

import core.services.current_semester
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('treso2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturerecue',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 15, 18, 32, 124632), null=True),
        ),
        migrations.CreateModel(
            name='FactureEmise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva', models.FloatField(default=0)),
                ('prix', models.FloatField(default=0)),
                ('destinataire', models.CharField(max_length=255)),
                ('date_creation', models.DateField(default=datetime.datetime(2023, 3, 30, 15, 18, 32, 125950), null=True)),
                ('nom_createur', models.CharField(max_length=255)),
                ('date_paiement', models.DateField(null=True)),
                ('date_due', models.DateField()),
                ('etat', models.CharField(choices=[('D', 'Due'), ('A', 'Annulée'), ('T', 'Partiellement payée'), ('P', 'Payée')], max_length=1)),
                ('semestre', models.ForeignKey(default=core.services.current_semester.get_current_semester, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semestre_actuelle', to='core.semestre')),
            ],
        ),
    ]
