# Generated by Django 3.2.16 on 2023-03-30 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treso2', '0003_auto_20230330_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturerecue',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 18, 24, 5, 326639), null=True),
        ),
    ]
