# Generated by Django 3.2.16 on 2023-04-02 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treso2', '0004_alter_facturerecue_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheque',
            old_name='facturerecue',
            new_name='facture',
        ),
        migrations.AlterField(
            model_name='factureemise',
            name='date_creation',
            field=models.DateField(default=datetime.date(2023, 4, 2), null=True),
        ),
        migrations.AlterField(
            model_name='facturerecue',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 13, 53, 43, 413408), null=True),
        ),
    ]
