# Generated by Django 3.2.16 on 2023-04-02 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treso2', '0005_auto_20230402_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturerecue',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 15, 22, 33, 111400), null=True),
        ),
    ]
