# Generated by Django 3.2.16 on 2023-04-03 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treso2', '0006_alter_facturerecue_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuivieModificationFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facuture_number', models.TextField(blank=True, default=None, null=True)),
                ('action', models.CharField(choices=[('C', 'Creation de la facture'), ('S', 'Suppretion de la facture'), ('M', 'Mis a jour de la facture')], max_length=1)),
                ('login', models.CharField(max_length=16)),
                ('date_creation', models.DateField(default=datetime.date(2023, 4, 3), null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='factureemise',
            name='date_creation',
            field=models.DateField(default=datetime.date(2023, 4, 3), null=True),
        ),
        migrations.AlterField(
            model_name='facturerecue',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 20, 19, 1, 375427), null=True),
        ),
    ]
