# Generated by Django 3.2.16 on 2023-04-03 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treso2', '0007_auto_20230403_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturerecue',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 20, 23, 4, 133573), null=True),
        ),
        migrations.AlterField(
            model_name='suiviemodificationfacture',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 20, 23, 4, 136752), null=True),
        ),
    ]
