# Generated by Django 3.2.16 on 2023-04-04 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treso2', '0008_auto_20230403_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureemise',
            name='date_creation',
            field=models.DateField(default=datetime.date(2023, 4, 4), null=True),
        ),
        migrations.AlterField(
            model_name='facturerecue',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 14, 22, 40, 838024), null=True),
        ),
        migrations.AlterField(
            model_name='suiviemodificationfacture',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 14, 22, 40, 840641), null=True),
        ),
    ]
