# Generated by Django 2.2.3 on 2019-08-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodiesWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=50)),
                ('picked_up', models.BooleanField(default=False)),
            ],
        ),
    ]
