# Generated by Django 2.2.3 on 2021-09-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shotgunDate', models.DateTimeField(default=None)),
                ('max_people', models.IntegerField(default=25)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('text', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserInShotgun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
    ]
