# Generated by Django 2.2.3 on 2021-09-29 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shotgun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinshotgun',
            name='id_creneau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shotgun.Creneau'),
        ),
    ]
