# Generated by Django 2.2.3 on 2021-09-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shotgun', '0002_userinshotgun_id_creneau'),
    ]

    operations = [
        migrations.AddField(
            model_name='creneau',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
