# Generated by Django 2.2.3 on 2019-10-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
