# Generated by Django 2.2.3 on 2019-11-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_survey_multi_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
