# Generated by Django 2.2.3 on 2020-01-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20191126_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyitem',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
