# Generated by Django 2.2.3 on 2019-08-16 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('perm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieFactureRecue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactureEmise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.CharField(max_length=255)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('nom_createur', models.CharField(max_length=255)),
                ('date_paiement', models.DateField(null=True)),
                ('date_due', models.DateField()),
                ('etat', models.CharField(choices=[('D', 'Due'), ('A', 'Annulée'), ('T', 'Partiellement payée'), ('P', 'Payée')], max_length=1)),
                ('semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Semestre')),
            ],
        ),
        migrations.CreateModel(
            name='ReversementEffectue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva', models.FloatField(default=0)),
                ('prix', models.FloatField(default=0)),
                ('date_effectue', models.DateField(null=True)),
                ('semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Semestre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactureRecue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva', models.FloatField(default=0)),
                ('prix', models.FloatField(default=0)),
                ('etat', models.CharField(choices=[('D', 'À payer'), ('R', 'À rembourser'), ('E', 'En attente'), ('P', 'Payée')], default='D', max_length=1)),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('date_paiement', models.DateField(default=None, null=True)),
                ('date_remboursement', models.DateField(default=None, null=True)),
                ('moyen_paiement', models.CharField(default=None, max_length=255, null=True)),
                ('personne_a_rembourser', models.CharField(default=None, max_length=255, null=True)),
                ('immobilisation', models.BooleanField(default=False)),
                ('remarque', models.TextField(default=None, null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='treso.CategorieFactureRecue')),
                ('perm', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='perm.Creneau')),
                ('semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Semestre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactureEmiseRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva', models.FloatField(default=0)),
                ('prix', models.FloatField(default=0)),
                ('nom', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treso.FactureEmise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('valeur', models.FloatField(default=0)),
                ('state', models.CharField(choices=[('E', 'Encaisse'), ('P', 'En cours'), ('A', 'Annulé'), ('C', 'Caution')], max_length=1)),
                ('destinataire', models.CharField(default=None, max_length=255, null=True)),
                ('date_encaissement', models.DateField(null=True)),
                ('date_emission', models.DateField(null=True)),
                ('commentaire', models.TextField(default=None, null=True)),
                ('facturerecue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='treso.FactureRecue')),
            ],
        ),
    ]
