# Generated by Django 2.2.3 on 2019-09-04 16:15

import core.services.current_semester
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factureemise',
            name='semestre',
            field=models.ForeignKey(default=core.services.current_semester.get_current_semester, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Semestre'),
        ),
        migrations.AlterField(
            model_name='facturerecue',
            name='semestre',
            field=models.ForeignKey(default=core.services.current_semester.get_current_semester, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Semestre'),
        ),
        migrations.AlterField(
            model_name='reversementeffectue',
            name='semestre',
            field=models.ForeignKey(default=core.services.current_semester.get_current_semester, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Semestre'),
        ),
    ]
