# Generated by Django 2.2.3 on 2020-02-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treso', '0002_auto_20190904_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturerecue',
            name='facture_number',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
