# Generated by Django 2.2.3 on 2021-02-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treso', '0004_auto_20200911_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturerecue',
            name='moyen_paiement',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
