# Generated by Django 2.2.1 on 2019-07-08 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('perm', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True)),
                ('login', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('asso', models.BooleanField(default=True)),
                ('nom_resp', models.CharField(default=None, max_length=255, null=True)),
                ('mail_resp', models.CharField(default=None, max_length=255, null=True)),
                ('state', models.CharField(choices=[('T', 'Traitée'), ('N', 'Non traitée')], default='N', max_length=1)),
                ('montantTTCMaxAutorise', models.FloatField(default=None, null=True)),
                ('semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('creneau', models.CharField(choices=[('M', 'Matin'), ('D', 'Déjeuner'), ('S', 'Soir')], max_length=2)),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perm.Perm')),
            ],
        ),
    ]
