# Generated by Django 2.2.1 on 2019-07-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perm',
            name='montantTTCMaxAutorise',
        ),
        migrations.RemoveField(
            model_name='perm',
            name='state',
        ),
        migrations.AddField(
            model_name='creneau',
            name='montantTTCMaxAutorise',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='creneau',
            name='state',
            field=models.CharField(choices=[('T', 'Traitée'), ('N', 'Non traitée')], default='N', max_length=1),
        ),
    ]
