# Generated by Django 2.2.3 on 2019-09-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='perm',
            new_name='creneau',
        ),
    ]
