# Generated by Django 2.2.1 on 2019-07-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0002_auto_20190711_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneau',
            name='perm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='perm.Perm'),
        ),
    ]
