# Generated by Django 2.2.3 on 2019-09-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0002_auto_20190903_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(auto_now_add=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perm.Article')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_first_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('served', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('id_transaction_payutc', models.IntegerField(default=0, unique=True)),
                ('id_rows_payutc', models.IntegerField(default=0)),
                ('id_buyer', models.IntegerField(default=0)),
                ('is_canceled', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perm.Menu')),
            ],
        ),
    ]
