# Generated by Django 2.2.1 on 2019-07-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0003_auto_20190713_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva', models.FloatField(default=0)),
                ('prix', models.FloatField(default=0)),
                ('id_payutc', models.IntegerField(default=None, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('ventes', models.IntegerField(default=0)),
                ('ventes_last_update', models.DateTimeField(default=None, null=True)),
                ('nom', models.CharField(max_length=255)),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perm.Creneau')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
