# Generated by Django 2.2.3 on 2019-09-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0005_auto_20190909_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='perm.Article'),
        ),
    ]
