# Generated by Django 2.2.3 on 2019-10-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_poste'),
        ('perm', '0006_auto_20190921_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astreinte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astreinte_type', models.CharField(choices=[('M1', 'Matin1'), ('M2', 'Matin2'), ('D1', 'Déjeuner1'), ('D2', 'Déjeuner2'), ('S', 'Soir')], max_length=1)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perm.Creneau')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Member')),
            ],
        ),
    ]
