# Generated by Django 2.2.3 on 2019-10-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0006_auto_20191022_1154'),
        ('perm', '0008_auto_20191023_1347'),
    ]

    operations = [
    ]
