# Generated by Django 2.2.3 on 2019-10-23 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0009_merge_20191023_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astreinte',
            name='astreinte_type',
            field=models.CharField(choices=[('M1', 'Matin 1'), ('M2', 'Matin 2'), ('D1', 'Déjeuner 1'), ('D2', 'Déjeuner 2'), ('S', 'Soir')], max_length=2),
        ),
        migrations.AlterField(
            model_name='astreinte',
            name='creneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astreintes', to='perm.Creneau'),
        ),
    ]
