# Generated by Django 2.2.3 on 2019-12-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0012_permhalloween'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedPerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('asso', models.BooleanField(default=True)),
                ('mail_asso', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('nom_resp', models.CharField(default=None, max_length=255, null=True)),
                ('mail_resp', models.CharField(default=None, max_length=255, null=True)),
                ('nom_resp_2', models.CharField(default=None, max_length=255, null=True)),
                ('mail_resp_2', models.CharField(default=None, max_length=255, null=True)),
                ('theme', models.CharField(default=None, max_length=255, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('membres', models.CharField(default=None, max_length=255, null=True)),
                ('periode', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='astreinte',
            name='commentaire',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
