# Generated by Django 2.2.3 on 2019-12-20 16:00

import core.services.current_semester
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191023_2221'),
        ('perm', '0014_requestedperm_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedperm',
            name='semestre',
            field=models.ForeignKey(default=core.services.current_semester.get_current_semester, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Semestre'),
        ),
    ]
