# Generated by Django 2.2.3 on 2019-12-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0016_requestedperm_founder_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedperm',
            name='ambiance',
            field=models.IntegerField(default=0),
        ),
    ]
