# Generated by Django 2.2.3 on 2019-12-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0017_requestedperm_ambiance'),
    ]

    operations = [
        migrations.AddField(
            model_name='perm',
            name='mail_resp_2',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perm',
            name='nom_resp_2',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
