# Generated by Django 2.2.3 on 2019-12-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0018_auto_20191223_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='perm',
            name='mail_asso',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
