# Generated by Django 2.2.3 on 2021-02-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0019_perm_mail_asso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default=None, max_length=10, null=True)),
                ('mail', models.CharField(default=None, max_length=255, null=True)),
                ('nouvo', models.BooleanField(default=False)),
                ('nb_resa', models.IntegerField(default=0)),
                ('nb_resa_conf', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goupe_id', models.CharField(default=None, max_length=10, null=True)),
                ('login_etu', models.ManyToManyField(to='perm.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.CharField(choices=[('EXT', 'Table exterieur'), ('INT', 'Table interieur')], max_length=3)),
                ('date_resa', models.CharField(default=None, max_length=10, null=True)),
                ('date_venu', models.CharField(default=None, max_length=10, null=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perm.Groupe')),
            ],
        ),
    ]
